language: python
python:
  - "3.4"
  - "3.5"
os:
  - linux
  - win
  # osx is not working at the moment on travis... try later.
  # - osx
# command to install dependencies
install:
  - pip install coveralls
  - python setup.py develop
# command to run tests
script:
  nosetests  --with-coverage
after_success:
  coveralls